import type { RawJob } from '../domain/job.schema.js';

interface MockSeed {
  id: string;
  company: string;
  title: string;
  location: string | null;
  remote: string | null;
  salary: string | null;
  experience: string | null;
  skills: string[];
  postedAt: string;
  description: string;
  /** Why this fixture exists — keeps the set honest as it grows. */
  covers: string;
}

const SEEDS: MockSeed[] = [
  {
    id: 'mock-001',
    company: 'Meridian Labs',
    title: 'Senior Backend Engineer',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹35-50 LPA',
    experience: '5-9 years',
    skills: ['TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'],
    postedAt: '2 days ago',
    description:
      '<p>We are building a high-throughput payments platform. You will own backend services end to end.</p><ul><li>5+ years building production Node.js/TypeScript services</li><li>Strong PostgreSQL and schema design</li><li>AWS (ECS, Lambda, RDS)</li><li>Experience with event-driven architectures</li></ul><p>Hybrid: 3 days a week in our Bengaluru office.</p>',
    covers: 'strong match, complete information',
  },
  {
    id: 'mock-002',
    company: 'Nordwind Systems',
    title: 'Staff Software Engineer, Platform',
    location: 'Remote (India)',
    remote: 'Fully remote',
    salary: '₹45-65 LPA',
    experience: '8+ years',
    skills: ['Go', 'Kubernetes', 'Terraform', 'PostgreSQL'],
    postedAt: '1 day ago',
    description:
      '<p>Own the internal developer platform used by 200 engineers.</p><ul><li>8+ years of backend experience</li><li>Deep Kubernetes and Terraform</li><li>Go preferred; strong engineers from other stacks welcome</li></ul><p>Fully remote within India.</p>',
    covers: 'remote, high seniority, partial stack mismatch',
  },
  {
    id: 'mock-003',
    company: 'Calyx Health',
    title: 'Full Stack Developer',
    location: 'Pune, India',
    remote: null,
    salary: 'Not disclosed',
    experience: '3-6 years',
    skills: ['React', 'Node.js', 'MongoDB'],
    postedAt: '3 days ago',
    description:
      '<p>Join our clinical data team building patient-facing tools.</p><ul><li>3-6 years full stack experience</li><li>React and Node.js</li><li>MongoDB or similar document store</li></ul>',
    covers: 'undisclosed salary — must not be penalised for it',
  },
  {
    id: 'mock-004',
    company: 'Vantage Retail Group',
    title: 'Junior Software Engineer',
    location: 'Noida, India',
    remote: 'On-site',
    salary: '₹4-6 LPA',
    experience: '0-2 years',
    skills: ['Java', 'Spring'],
    postedAt: '5 days ago',
    description:
      '<p>Entry level role for fresh graduates. Training provided on Java and Spring Boot.</p><p>Work from office, 6 days a week.</p>',
    covers: 'far below candidate seniority and salary floor',
  },
  {
    id: 'mock-005',
    company: 'Helios Analytics',
    title: 'Senior Engineer',
    location: 'Hyderabad, India',
    remote: null,
    salary: null,
    experience: null,
    skills: [],
    postedAt: '1 day ago',
    description:
      '<p>Looking for a senior engineer to join a fast-moving team. Competitive package. Apply to know more.</p>',
    covers: 'extremely vague — should produce LOW confidence, not a low score',
  },
  {
    id: 'mock-006',
    company: 'Quantile Capital',
    title: 'Entry Level Backend Engineer (10+ years experience required)',
    location: 'Mumbai, India',
    remote: null,
    salary: '₹18-22 LPA',
    experience: '10+ years',
    skills: ['Python', 'Django'],
    postedAt: '4 days ago',
    description:
      '<p>This is an entry-level position on our junior engineering track.</p><ul><li>Minimum 10 years of backend experience required</li><li>Candidates must be recent graduates</li><li>Lead a team of 5 engineers</li></ul>',
    covers: 'internally contradictory — should set uncertainties.conflicting',
  },
  {
    id: 'mock-007',
    company: 'Brightpath Education',
    title: 'Technical Support Engineer',
    location: 'Chennai, India',
    remote: 'Hybrid',
    salary: '₹8-12 LPA',
    experience: '2-5 years',
    skills: ['SQL', 'Zendesk'],
    postedAt: '6 days ago',
    description:
      '<p>Provide L2 technical support to enterprise customers. Troubleshoot API issues and escalate bugs.</p>',
    covers: 'adjacent but off-target role — deterministic title filter',
  },
  {
    id: 'mock-008',
    company: 'Orbit Fintech',
    title: 'Backend Engineer (Node.js)',
    location: 'Remote',
    remote: 'Remote',
    salary: '$70,000 - $95,000',
    experience: '4-8 years',
    skills: ['Node.js', 'TypeScript', 'Redis', 'Kafka', 'AWS'],
    postedAt: 'today',
    description:
      '<p>Build the ledger service at the core of our payments product.</p><ul><li>4-8 years backend experience</li><li>Node.js and TypeScript in production</li><li>Kafka or similar streaming systems</li><li>Redis, PostgreSQL</li></ul><p>Remote-first, occasional travel.</p>',
    covers: 'strong match, USD salary, posted today',
  },
  {
    id: 'mock-009',
    company: 'Ironclad Defence Systems',
    title: 'Software Engineer - Weapons Systems',
    location: 'Bengaluru, India',
    remote: 'On-site',
    salary: '₹25-35 LPA',
    experience: '4-8 years',
    skills: ['C++', 'Embedded'],
    postedAt: '3 days ago',
    description:
      '<p>Develop embedded control software for defence applications. Security clearance required.</p>',
    covers: 'excluded industry',
  },
  {
    id: 'mock-010',
    company: 'Lumen Commerce',
    title: 'Senior Backend Engineer',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹35-50 LPA',
    experience: '5-9 years',
    skills: ['TypeScript', 'Node.js', 'PostgreSQL'],
    postedAt: '2 days ago',
    description:
      '<p>Scale our order management system to handle peak season traffic.</p><ul><li>5+ years backend engineering</li><li>TypeScript and Node.js</li><li>PostgreSQL at scale</li></ul>',
    covers: 'near-duplicate of mock-001 in shape but a different company',
  },
  {
    id: 'mock-011',
    company: 'Meridian Labs',
    title: 'Sr. Backend Engineer',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹35-50 LPA',
    experience: '5-9 years',
    skills: ['TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    postedAt: '2 days ago',
    description:
      '<p>We are building a high-throughput payments platform. You will own backend services end to end.</p><ul><li>5+ years building production Node.js/TypeScript services</li><li>Strong PostgreSQL and schema design</li><li>AWS (ECS, Lambda, RDS)</li></ul>',
    covers: 'fuzzy duplicate of mock-001 ("Sr." vs "Senior", same company/location)',
  },
  {
    id: 'mock-012',
    company: 'Aperture Media',
    title: 'Senior Frontend Engineer',
    location: 'Gurugram, India',
    remote: 'Hybrid',
    salary: '₹28-40 LPA',
    experience: '5-8 years',
    skills: ['React', 'TypeScript', 'Next.js'],
    postedAt: '2 days ago',
    description:
      '<p>Own our editorial publishing interface used by 3,000 journalists.</p><ul><li>5+ years frontend</li><li>React, Next.js, TypeScript</li><li>Strong accessibility practice</li></ul>',
    covers: 'partially relevant role, different specialisation',
  },
  {
    id: 'mock-013',
    company: 'Cobalt Logistics',
    title: 'Engineering Manager - Backend',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹55-75 LPA',
    experience: '10-15 years',
    skills: ['Leadership', 'Node.js', 'System Design'],
    postedAt: '7 days ago',
    description:
      '<p>Lead two backend squads. 70% people management, 30% technical direction.</p><ul><li>10+ years, including 3+ managing engineers</li></ul>',
    covers: 'management track, experience well above candidate',
  },
  {
    id: 'mock-014',
    company: 'Stillwater AI',
    title: 'Backend Engineer, ML Infrastructure',
    location: 'Remote (Global)',
    remote: 'Remote',
    salary: '₹40-60 LPA',
    experience: '5+ years',
    skills: ['Python', 'Kubernetes', 'PyTorch', 'gRPC'],
    postedAt: '1 day ago',
    description:
      '<p>Build the serving layer for our model inference platform.</p><ul><li>5+ years backend</li><li>Python, Kubernetes</li><li>Familiarity with ML serving (Triton, vLLM) a plus, not required</li></ul>',
    covers: 'good match, skills partially outside profile',
  },
  {
    id: 'mock-015',
    company: 'Pinewood Consultancy',
    title: 'URGENT!!! Backend Developer - Immediate Joiners Only',
    location: 'Ahmedabad, India',
    remote: 'On-site',
    salary: '₹6-9 LPA',
    experience: '3-5 years',
    skills: ['Node.js', 'MySQL'],
    postedAt: '1 day ago',
    description:
      '<p>URGENT REQUIREMENT. Immediate joiners only. Bond of 2 years required. Salary as per market standards.</p>',
    covers: 'noisy title, below salary floor, excluded keyword candidate',
  },
  {
    id: 'mock-016',
    company: 'Tessellate Cloud',
    title: 'Principal Software Engineer',
    location: 'Remote (India)',
    remote: 'Fully remote',
    salary: '₹60-85 LPA',
    experience: '12+ years',
    skills: ['Distributed Systems', 'Go', 'AWS'],
    postedAt: '2 days ago',
    description:
      '<p>Set technical direction for our multi-region storage platform.</p><ul><li>12+ years designing distributed systems</li></ul>',
    covers: 'experience demand far above candidate',
  },
  {
    id: 'mock-017',
    company: 'Verdant Agritech',
    title: 'Software Engineer II',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹22-30 LPA',
    experience: '3-6 years',
    skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Kafka'],
    postedAt: '4 days ago',
    description:
      '<p>Build supply-chain services connecting 40,000 farmers to buyers.</p><ul><li>3-6 years backend engineering</li><li>Java and Spring Boot</li><li>Kafka, PostgreSQL</li></ul>',
    covers: 'reasonable match, different primary language',
  },
  {
    id: 'mock-018',
    company: 'Halcyon Travel',
    title: 'Senior Software Engineer',
    location: 'Berlin, Germany',
    remote: 'On-site',
    salary: '€75,000 - €95,000',
    experience: '5-8 years',
    skills: ['TypeScript', 'Node.js', 'GraphQL'],
    postedAt: '3 days ago',
    description:
      '<p>Join our booking platform team in Berlin. Relocation support and visa sponsorship available.</p><ul><li>5+ years Node.js/TypeScript</li><li>GraphQL API design</li></ul>',
    covers: 'strong skill match, incompatible location, visa question',
  },
  {
    id: 'mock-019',
    company: 'Northgate Insurance',
    title: 'Backend Developer',
    location: 'Kolkata, India',
    remote: null,
    salary: '₹15-20 LPA',
    experience: null,
    skills: ['Node.js', 'Express', 'MySQL'],
    postedAt: '8 days ago',
    description:
      '<p>Maintain and extend our policy administration APIs. Legacy modernisation work.</p><ul><li>Node.js and Express</li><li>MySQL</li></ul>',
    covers: 'unstated experience — must be unknown, not zero',
  },
  {
    id: 'mock-020',
    company: 'Foundry Digital',
    title: 'Senior Node.js Engineer',
    location: 'Remote (India)',
    remote: 'Work from home',
    salary: '₹38-52 LPA',
    experience: '6-10 years',
    skills: ['Node.js', 'TypeScript', 'AWS', 'PostgreSQL', 'Docker', 'Kubernetes'],
    postedAt: 'today',
    description:
      '<p>Lead backend development for our white-label commerce platform.</p><ul><li>6+ years Node.js in production</li><li>TypeScript, PostgreSQL</li><li>AWS and containerised deployments</li><li>Kubernetes experience valued</li></ul><p>Fully remote within India.</p>',
    covers: 'excellent match on every dimension',
  },
  {
    id: 'mock-021',
    company: 'Slate & Roan Recruiters',
    title: 'Multiple Backend Openings - Top MNCs',
    location: 'Multiple Locations',
    remote: null,
    salary: 'Not disclosed',
    experience: '2-12 years',
    skills: [],
    postedAt: '1 day ago',
    description:
      '<p>We have multiple openings across top MNCs for backend developers. Send your CV to know more. Experience 2-12 years. Locations across India.</p>',
    covers: 'recruiter aggregate posting — vague, wide band, should be low confidence',
  },
  {
    id: 'mock-022',
    company: 'Cindermark Gaming',
    title: 'Backend Engineer - Real Money Gaming',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹30-45 LPA',
    experience: '4-8 years',
    skills: ['Node.js', 'Redis', 'PostgreSQL'],
    postedAt: '5 days ago',
    description:
      '<p>Build wallet and transaction services for our real-money gaming platform. High concurrency, strict audit requirements.</p>',
    covers: 'good technical match in a potentially excluded industry',
  },
  {
    id: 'mock-023',
    company: 'Aurelia Systems',
    title: 'Software Development Engineer III',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹32-44 LPA',
    experience: '5-8 years',
    skills: ['TypeScript', 'Node.js', 'GraphQL', 'PostgreSQL', 'AWS'],
    postedAt: '2 days ago',
    description:
      '<p>Own core services in our B2B SaaS platform.</p><ul><li>5-8 years building backend services</li><li>TypeScript/Node.js</li><li>GraphQL and REST API design</li><li>PostgreSQL, AWS</li></ul><p>Hybrid, 2 days in office.</p>',
    covers: 'strong match, non-obvious title level',
  },
  {
    id: 'mock-024',
    company: 'Kestrel Freight',
    title: 'DevOps Engineer',
    location: 'Bengaluru, India',
    remote: 'Hybrid',
    salary: '₹25-38 LPA',
    experience: '4-7 years',
    skills: ['Terraform', 'AWS', 'Kubernetes', 'CI/CD'],
    postedAt: '3 days ago',
    description:
      '<p>Own our deployment pipelines and cloud infrastructure.</p><ul><li>Terraform, AWS, Kubernetes</li><li>Build and maintain CI/CD</li></ul>',
    covers: 'adjacent discipline — tests title relevance threshold',
  },
  {
    id: 'mock-025',
    company: 'Marrow & Finch Legal',
    title: 'Legal Operations Associate',
    location: 'Mumbai, India',
    remote: 'On-site',
    salary: '₹10-14 LPA',
    experience: '2-5 years',
    skills: ['Contract Review'],
    postedAt: '4 days ago',
    description:
      '<p>Support our legal team with contract lifecycle management and vendor onboarding.</p>',
    covers: 'entirely unrelated role — must be filtered before any LLM call',
  },
];

export function mockRawJobs(sourceName = 'mock'): RawJob[] {
  return SEEDS.map((seed) => ({
    source: sourceName,
    externalId: seed.id,
    company: seed.company,
    title: seed.title,
    description: seed.description,
    location: seed.location,
    remote: seed.remote,
    salary: seed.salary,
    experience: seed.experience,
    skills: seed.skills,
    url: `https://example-jobs.test/${sourceName}/${seed.id}`,
    applicationUrl: `https://example-jobs.test/${sourceName}/${seed.id}/apply`,
    postedAt: seed.postedAt,
    rawData: { covers: seed.covers },
  }));
}

export const MOCK_JOB_COUNT = SEEDS.length;
